### ISSUE TITLE
Does not work inside Panels (or Tabs)

### ISSUE THREAD

**Issue by Stiropor** [kirschbaum-development/nova-inline-relationship#10]
This looks amazing but having problems when using it inside Nova's Panel (or tabs, using eminiarts/nova-tabs). There are no error or anything on saving, but it doesn't save any changes or new values. My code is pretty simple:

```php
// Product resource
public function fields(Request $request)
{
	return [
		new Panel('Product', [
			ID::make()->sortable(),
			Text::make('Title', 'title'),
		]),
		new Panel('Discounts', [
			HasMany::make('Discounts', 'discounts', ProductDiscount::class)->inline(),
		])
	];
}

// ProductDiscount resource
public function fields(Request $request)
{
	return [
		ID::make(),
		BelongsTo::make ('Product', 'product', Product::class),
		Number::make('Amount', 'amount'),
		Number::make('Discount', 'price_discount'),
	];
}
```

Any ideas?

**Comment by navneetrai** [comment]
@Stiropor Are you able to create new `ProductDiscount` when adding a new `Product` model?

**Comment by Stiropor** [comment]
@navneetrai Just tested it - no if ProductDiscount relation is inside Panel or Tabs. If I put it outside it works fine.

**Comment by khalil-htme** [comment]
confirmed that this is a major problem im having also, please fix it :(

**Comment by khalil-htme** [comment]
@navneetrai when can we get a fix for this?

**Comment by vFire** [comment]
Same problems occurs, waiting for updated.

**Comment by vFire** [comment]
Find the inlineRelationshipObserver.php, replace the following function:

>     protected function getModelRelationships(Model $model)
    {
        $relationships = [];
        foreach (Nova::newResourceFromModel($model)->fields(request()) as $key => $value) {
            if($value->component === 'inline-relationship'){
                $relationships[] = $value->attribute;
            }else if($value->component === 'panel'){
                foreach ($value->data as $k => $v) {
                    if($v->component === 'inline-relationship'){
                        $relationships[] = $v->attribute;
                    }
                }
            }
        }
        //dd($relationships);
        // $relationships = collect(Nova::newResourceFromModel($model)->fields(request()))->filter(function ($value) {
        //     return $value->component === 'inline-relationship';
        // })->pluck('attribute')->all();

        return $relationships;
    }

that's it.

**Comment by BobbyBorisov** [comment]
@vFire hey! i am trying this package and wondering whether i can do nested inline relationships? User-> Posts -> Comments?
