### ISSUE TITLE
hasOne behavior

### ISSUE THREAD

**Issue by bilogic** [kirschbaum-development/nova-inline-relationship#101]
Hi,

I have this: `sales_orders` `hasOne` `customer`, i.e. `customers.sales_order_id` points to `sales_orders.id`
So when I add `HasOne::make("customer")->inline()` in the `SalesOrder` Nova resource, wouldn't it make more sense to show the customer's name in the `index` view instead of showing `1 customer`?

`sales_orders` and `customers` may not be the best example here, but my point is, why not show the contents instead of just the count, since it `hasOne` only. Thank you.

**Comment by luisdalmolin** [comment]
If this is still something you would want, feel free to submit a PR.
