### ISSUE TITLE
Nova 4

### ISSUE THREAD

**Issue by alasriaj** [kirschbaum-development/nova-inline-relationship#107]
Please Add Support Nova4

**Comment by AbdullahGhanem** [comment]
up

**Comment by nbartokos** [comment]
some updates when the nova 4 version will be available?

**Comment by sergiomarrerogonzalez** [comment]
> some updates when the nova 4 version will be available?
> 
> I installed the latest version, but then every page in my nova app is only blank white.

@nbartokos I have this same issue with black page... where you able to solve it?

**Comment by wilkerwma** [comment]
we are working on Novas 4's migration under this draft PR: https://github.com/kirschbaum-development/nova-inline-relationship/pull/113. We should be releasing this soon.

**Comment by jmverges** [comment]
+1

**Comment by luisdalmolin** [comment]
Nova 4 support is here: https://github.com/kirschbaum-development/nova-inline-relationship/releases/tag/2.0.0
