### ISSUE TITLE
$timestamps = false ignored.

### ISSUE THREAD

**Issue by jeffizzle** [kirschbaum-development/nova-inline-relationship#118]
When saving an inline relationship, I'm getting an error saying `updated_at` doesn't exist in the parent model's table even thought I've explicitly set `$timestamps = false` in the model.

I saw that there already exists a PR with the solution. Any chance of merging?
https://github.com/kirschbaum-development/nova-inline-relationship/pull/71

**Comment by luisdalmolin** [comment]
This is going to be included in the next version.
