### ISSUE TITLE
use of hardcoded 'id'

### ISSUE THREAD

**Issue by sjess** [kirschbaum-development/nova-inline-relationship#13]
Hi there,

would you be so kind and change

`'models' => $this->value ? $this->value->pluck('id')->all() : [],`

to

`'models' => $this->value ? (is_a($this->value, 'Illuminate\Database\Eloquent\Collection') ? $this->value->pluck($this->value->modelKeys())->all() : $this->value->pluck($this->value->getKeyName())->all()) : [],`

This way the col 'id' is not hardcoded and all is more flexible.

thx

**Comment by sjess** [comment]
ok, this works with HasOne ... but not HasMany ...

**Comment by kirschbaum** [comment]
Thanks @sjess! We'll take a look at this.

**Comment by brandonferens** [comment]
@sjess That is a great suggestion. Would you please issue a PR with the fix?

**Comment by brandonferens** [comment]
@sjess I have issued PR #32 that resolves this issue.
