### ISSUE TITLE
Field lable design and relation belongs to field not rendering

### ISSUE THREAD

**Issue by 3owlcristian** [kirschbaum-development/nova-inline-relationship#131]
Hi, 

I am facing following problem with the latest laravel nova:

![image](https://github.com/kirschbaum-development/nova-inline-relationship/assets/80748923/defcffa5-bf27-46a1-a04d-d0fd47a17920)

also, the relation belongs to the field inside it, somehow not rendering, and needs to use normal select. But Select with searchable is also not working!

`Select::make('County', 'county_id')->searchable()->options($counties_arr)->displayUsingLabels(),`

**Comment by luisdalmolin** [comment]
The code snippet you added doesn't seem to have anything to do with this package. Please submit a more detailed issue if you want some support. Ideally, with a reproduction repo.
