### ISSUE TITLE
Support for MorphTo relationship

### ISSUE THREAD

**Issue by fntneves** [kirschbaum-development/nova-inline-relationship#14]
Hello,

Thank you for this package.

Are you considering to add support for inline MorphTo relationship?

**Comment by michaelfox** [comment]
Hi @fntneves! Thank you for this suggestion. We've been busy but are hoping to carve some time out soon.

**Comment by brandonferens** [comment]
@fntneves The `MorphTo` inline relationship is on the roadmap, but currently we are focusing on pivot fields. 

Please feel free to issue a PR if you'd like to see this implemented sooner than later. Thanks!

**Comment by brandonferens** [comment]
@fntneves We have this on our roadmap project at https://github.com/kirschbaum-development/nova-inline-relationship/projects/1
