### ISSUE TITLE
HasOne::make Display name not working

### ISSUE THREAD

**Issue by antlusher** [kirschbaum-development/nova-inline-relationship#15]
As title - I can't seem to get the custom display name to work.

 HasOne::make('Comms Preferance', 'Comms_Preference', CommsPreference::class)
            ->inline()
            ->onlyOnForms()

![Screen Shot 2019-10-12 at 22 35 45](https://user-images.githubusercontent.com/2495026/66707941-b3b23000-ed40-11e9-87fe-d175a5cdd90e.png)

As in screen I'm getting the method name, and not the first param thats passed (Custom name). 

Is there any additional code I'm missing?

All the best

**Comment by antlusher** [comment]
Agh. Kinda worked it out. It's the 'singular' method. Would it be an idea to strip out underscores?

**Comment by kamilkozak** [comment]
same issue here

**Comment by michaelfox** [comment]
Hi @antlusher and @kamilkozak -- Thanks for the feedback on this issue. We've been busy but are hoping to carve some time out soon.

If you've already put in the work we would appreciate your contribution–via pull request or even just a description of your solution. 

Thanks again!

**Comment by brandonferens** [comment]
> Agh. Kinda worked it out. It's the 'singular' method. Would it be an idea to strip out underscores?

@antlusher What exactly do you mean by "singular" method?

Have you figured out the issue or does this appear to be a bug ?

**Comment by brandonferens** [comment]
@antlusher This issue is resolved and will be released in the next tagged version which will come shortly!
