### ISSUE TITLE
hideFromIndex() doesn't work with relation fields marked as inline()

### ISSUE THREAD

**Issue by tumainimosha** [kirschbaum-development/nova-inline-relationship#20]
I have an inline relationship on a nova resource that I would like to hide from displaying on index.

This is what I implemented

```
 BelongsTo::make('Solution', 'solution', Solution::class)
        ->hideFromIndex()
        ->inline()
        ->updateRules('sometimes'),
```

However, the field is still visible on index.

On commenting out the `inline()` method call, it works as expected by removing the field from index view.

This seems to be related to issue #19 on controlling visibility of inline relation field

**Comment by Medalink** [comment]
A work-a-round for this is to chain inline *before* you hide:

`HasMany::make('Options', 'options', Option::class)
    ->inline()
    ->hideFromIndex(),`

That works for me!
