### ISSUE TITLE
Error "Driver [] is not supported" when trying to use Image

### ISSUE THREAD

**Issue by hotmeteor** [kirschbaum-development/nova-inline-relationship#22]
I have a `hasMany` relationship, and each item in that relationship uses an `Image` field. However, I get a `Driver [] is not supported` error whenever I try to use it.

I've tried with both `local` and `s3` settings but no dice. Any ideas?

**Comment by michaelfox** [comment]
Hi @hotmeteor! Thanks for the feedback on this issue. We've been busy but are hoping to carve some time out soon.

**Comment by brandonferens** [comment]
@hotmeteor Can you please provide more information regarding this issue? I'd like to see a dump of the error from the log and any thing else that may help us figure this issue out.

**Comment by brandonferens** [comment]
@hotmeteor This seems to be an issue relating to a server problem where the proper drivers may not be installed. We are not able to replicate this issue and aren't implementing anything within this package that would related to drivers in this way. 

We are going to close this for now, but if this problem persists or if you can provide some more specific information or log dumps that will help us replicate the issue, we will gladly open this back up and work on a fix!

Thanks so much for using this package, we really appreciate it!
