### ISSUE TITLE
Cannot see second nesting

### ISSUE THREAD

**Issue by BobbyBorisov** [kirschbaum-development/nova-inline-relationship#23]
Hey guys, thanks for the great package! I have the following issue. I have setup like this: User -> Posts -> Comments. I have setup the Laravel Nova Resource and Eloquent Model for all of them and have HasMany..->inline() in User and Post Nova Resource but somehow i cannot see Comments when creating Users. I can only see Posts. Is it intended behavior and i cannot do nesting like this?

**Comment by michaelfox** [comment]
HI @BobbyBorisov! Thanks for the feedback on this issue. We've been busy but are hoping to carve some time out soon.

**Comment by brandonferens** [comment]
@BobbyBorisov Currently Nova does not support `HasManyThrough` functionality at this point. We may look into adding this behavior if that field type is implemented in Nova's core.

Thanks!
