### ISSUE TITLE
BelongsToMany

### ISSUE THREAD

**Issue by timcv** [kirschbaum-development/nova-inline-relationship#3]
Hi,

Would it be possible to support BelongsToMany relationships?

And also add a button for selecting existing objects?

//Tim

**Comment by navneetrai** [comment]
@timcv Thanks for you interest on Nova Inline Relationship. We definitely have plans to include `BelongsToMany` and `MorphedByMany`.

> And also add a button for selecting existing objects?
We have to investigate how it will affect the inline nature of things. Our aim is not to replicate what is already present in Nova, but to add new ways to make it easier for user to manage child models with parents.

So, If it felt too similar to what Nova is already providing with the non-inline version of a relationship then we might come up with something different.

**Comment by dormadekhin** [comment]
It would be very cool if such support appears! and not only select the existing one, but also write fields to the pivot table
perhaps this can be done if to do a resource nova for the linking table, what do you think?

**Comment by navneetrai** [comment]
@dormadekhin that is the plan. These relationships are next in line.

We are looking into finding the most intuitive ways to add these fields and pivot data inline.

**Comment by kculmback** [comment]
Would love to see this too 👍🏻

**Comment by brandonferens** [comment]
This issue duplicates #26 which is on our roadmap. Let's continue the discussion on that issue!
