### ISSUE TITLE
Unable to assign already created user to new post

### ISSUE THREAD

**Issue by saqueib** [kirschbaum-development/nova-inline-relationship#4]
I have a **Post** resource which has a **belongsTo** relation for a user

```php
BelongsTo::make('User')
    ->rules('required')
    ->searchable()
    ->inline()
```

I used inline-relationship and it works great for `edit` & `details view`, but when I try to add a new record it gives me error since user email id is already exists in database. 

If you can give some dropdown of all the user already in system along with your `Add new user` button that will be great.

Currently I cant assign new post to already existing user.

```
Integrity constraint violation: 1062 Duplicate entry 'saqueib@example.com' for key 'users_email_unique'
```

I also tried creating two fields like this 

```php
 BelongsTo::make('User')
    ->rules('required')
    ->searchable()
    ->sortable()
    ->help('Associate this story with a user')
    ->hideWhenCreating()
    ->hideFromIndex()
    ->inline()
,

BelongsTo::make('User')
    ->rules('required')
    ->searchable()
    ->sortable()
    ->help('Associate this story with a user')
    ->hideFromIndex()
,
```

But its failing when I search for a user from dropdown 

```
Cannot access private property KirschbaumDevelopment\NovaInlineRelationship\NovaInlineRelationship::$resourceClass
```

Let me know is there any other way to do it. Keep up the great work 👍

**Comment by navneetrai** [comment]
Hi @saqueib 

Thanks for your interest in Nova Inline Relationship. 

The reason for not including a model dropdown in `BelongsTo` is that it brings it too close to non-inline version of `BelongsTo` component. Our focus is primarily towards adding a new way to add related model data inline, instead of replicating what is already present in nova.

We are working on a few alternate approaches to keep things inline. I will update this ticket once we push an update.

**Comment by brandonferens** [comment]
@saqueib This is an interesting issue and I'm not sure that we will be able to accomplish this. As @navneetrai mentioned we are focused with this package on creating a new or updating an existing attached relationship.

It appears you are trying to create a new post and attach it to a user. Perhaps you could start from the user and attach a new post? Or just remove the inline part when you are creating a post?

**Comment by saqueib** [comment]
@brandonferens Thanks for the great package, I did remove it from creating screen 👍
