### ISSUE TITLE
Parent id not being passed to child

### ISSUE THREAD

**Issue by AshleyMinshall** [kirschbaum-development/nova-inline-relationship#50]
Hi thanks for the Awesome package!

I am having trouble saving my children when using HasOne and HasMany fields.
Question -> hasOne -> solution
Question -> hasMany -> options
When the create form is submitted, I get an error saying the the question_id, (a field present on both solution and options) is not present. 

Is there a way to add it to the create call? The same thing happens when adding a child when editing.

Thanks
Ashley

Ps. I hope I'm not going crazy but I'm pretty sure it was working when creating, but not updating and then after making some changes, it no longer worked.

**Comment by AshleyMinshall** [comment]
My mistake, I realized it was a user error.
In my options table I have a question_id column that I was expecting to be filled out by the solution relation. However the solution relation is Question -> belongsTo -> option -> where -> question.solution_id = options.id.

So it would have never worked.

Thanks again, helps by writing it out
Ashley

**Comment by brandonferens** [comment]
@AshleyMinshall Glad you figured it out. Let us know if you have any other questions!

**Comment by AshleyMinshall** [comment]
Hi @brandonferens!
Thanks for the reply, means alot. I also left a comment here https://github.com/kirschbaum-development/nova-inline-relationship/issues/21#issuecomment-580259897 

If you could assist with that, that would be awesome :)

Thanks
Ashley
