### ISSUE TITLE
Can I somehow pre-fill inline relationships at creation form?

### ISSUE THREAD

**Issue by 4n70w4** [kirschbaum-development/nova-inline-relationship#57]
Case: on create resource form need automatically pre-fill inline relationships with some values.

**Comment by brandonferens** [comment]
@4n70w4 There are quite a few discussions revolving around this idea. As of now, Nova doesn't support this functionality out of the box and as such we won't as well.

That being said, there are quite a few ways of handling this. You can pass in meta values, create macros, etc. Give this thread a read: https://github.com/laravel/nova-issues/issues/58. There are quite a few good suggestions on getting this to work.

Thanks!
