### ISSUE TITLE
Change `HasOne`, `MorphOne` rendering

### ISSUE THREAD

**Issue by Anticom** [kirschbaum-development/nova-inline-relationship#6]
It would be nice if `required` rule was detected on a resource and `HasOne` and `MorphOne` relationships would be inlined by default then without having to press "Add new <resource>" button.

**Comment by navneetrai** [comment]
Hi @Anticom 

Thanks for the suggestion and interest in Nova Inline Relationship.
 
We are already detecting the type and relationship and that is why `Add More` button in singular relationship won't allow you to add more then one items.

The reason to not add a field by default are two folds:-
1. It keeps the interface uniform between the relationships.
2. not everyone wants to add the child relationship all the time. We felt that as this is an optional thing, it should be initiated by a user action.

We are discussing the possibility of allowing this on relationships using a meta property.

**Comment by Anticom** [comment]
Hi @navneetrai 

Thanks for the reply.

I do get your point about consistency in the UI, however if I as developer express a required relationship this should be reflected in the UI as well IMO.

Basically was I'd like to solve with your package is, what Doctrine can do via [inheritance mapping](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html). Since Eloquent has no such functionality I wanted to go fo morphing relationships and your package allows me to inline the fields into a single view for the resource which basically emulates the inheritance mapping behaviour, at least visually.

That being said I find it more confusing for a user having to click a button to add the (anyway required) fields to be able to save that resource.

**Comment by nemrutco** [comment]
+1
In my case, i also got few required fields in my inline relationship. Since relationship form is not on DOM before you click the button, there is no any validation. So i will get missing relationship id sql error. It would be nice if there is a way to switch by default show hide switch option. Something like simple as

```php
->open()
```
or complex as
```php
->displayIf(function(){...})
```

**Comment by Anticom** [comment]
> +1
> In my case, i also got few required fields in my inline relationship. Since relationship form is not on DOM before you click the button, there is no any validation. So i will get missing relationship id sql error. It would be nice if there is a way to switch by default show hide switch option. Something like simple as
> 
> ```
> ->open()
> ```
> 
> or complex as
> 
> ```
> ->displayIf(function(){...})
> ```

I like that idea as well instead of automagic required detection. It's a bit more verbose but captures the intent better and doesn't hide the initially requested behaviour.

**Comment by brandonferens** [comment]
@Anticom @nemrutco I just created PR #30 to solve this issue. Please feel free to look over it if you would like to. As soon as it is approved and merged it will get included in the next tagged release!

**Comment by brandonferens** [comment]
PR #30 has been approved and merged.

**Comment by nemrutco** [comment]
updates not released to Packagist yet?

**Comment by brandonferens** [comment]
@nemrutco We are hoping to release it today.
