### ISSUE TITLE
Use `$title` for `HasOne`, `MorphOne`

### ISSUE THREAD

**Issue by Anticom** [kirschbaum-development/nova-inline-relationship#7]
For `HasOne` and `MorphOne` relationships it would make sense to use the `$title` attribute from the related resource instead of showing "1 <Resource>(s)".

**Comment by navneetrai** [comment]
Hi @Anticom 

I agree with this. In fact an update is already on the way to use title in the index view and based on the number of Item show singular of plural title.

**Comment by Anticom** [comment]
Hi @navneetrai maybe you can just default to using the related `$title` but give it an option to override either in the `->inline()` method or via an attribute in the related class.
Something along the lines
```php
// a resource
// ...
  /**
   * Will override the default implementation to retrieve the inline title
   */
  public function getInlineTitle()
  {
    return 'foo';
  }
// ...
```

**PS:** If you like me to contribute (especially on my issues) just give me a heads-up and I will try to find the time to send some PRs :)

**Comment by brandonferens** [comment]
@Anticom I just issued a PR that solves this issue. It auto-determines if it is singular and as a result changes the plurality of the label and displays the number conditionally.

Feel free to look over the PR and make suggestions. Thanks!

**Comment by brandonferens** [comment]
@Anticom PR #31 has been merged and will be released in the next tagged version!

**Comment by Anticom** [comment]
@brandonferens Sorry for the late reply.
Thanks for implementing the suggestion, it solved my problem!

**Comment by genesiscz** [comment]
How about https://github.com/kirschbaum-development/nova-inline-relationship/issues/33 ? It still shows the count with singular label instead of a link as nova uses
